### ISSUE TITLE
Instancja klasy CDTP

### ISSUE THREAD

**Issue by Wruczek** [grzegorz2047/CommunityDrivenPlugin#4]
Czy nie lepiej jest zrobić główną instancję a potem pobierać ją gdy jest potrzebna?

``` java
package pl.craftgames.communityplugin.cdtp;

public class CDTP extends JavaPlugin {

    private static CDTP instance;

    @Override
    public void onEnable() {
        instance = this;
    }

    public static CDTP getInstance() {
        return instance;
    }
}
```

Jest to stosowane między innymi w FunnyGuilds.
Myślę, że dzięki takiemu rozwiązaniu późniejsze kodowanie jest po prostu łatwiejsze.

Co o tym sądzisz?

**Comment by grzegorz2047** [comment]
Czy jakoś wielce łatwiejsze? Korzystałem kiedyś z singletonu, ale jakoś tak bezpieczniej dla mnie jest korzystać z konstruktorów, żeby przekazywać referencje. Statyczne wywołanie jest trochę wygodniejsze, ale minusy też posiada.

**Comment by Wruczek** [comment]
Rozumiem, czyli zostaje tak jak jest.

**Comment by grzegorz2047** [comment]
Mi to nie robi różnicy, ale wydaje się mój sposób jakoś bardziej elegancko xd

**Comment by TheMolkaPL** [comment]
Tu chodzi głównie o to, że inna implementacja niż CraftBukkit musi odrzucić wieloinstancjowość przy posiadaniu pluginów z singlestone.

Przekazywanie klasy w konstruktorze jest bardziej "przyszłościowe" do przyszłych poważniejszych zmian w kodzie.
